# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DL3AAgpb7g31xuGfdE4cxOm10_K55mH7
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# 
# import streamlit as st
# import pandas as pd
# 
# st.set_page_config(page_title="CareerPilot-X", page_icon="🚀")
# 
# careers = {
#     "AI/ML Engineer": ["python", "machine learning", "numpy", "pandas", "tensorflow", "nlp"],
#     "Data Scientist": ["python", "pandas", "numpy", "statistics", "machine learning"],
#     "Data Analyst": ["python", "pandas", "excel", "sql", "statistics"],
#     "Software Developer": ["python", "java", "dsa", "oops", "git"],
#     "Web Developer": ["html", "css", "javascript", "react", "git"],
#     "Cybersecurity Analyst": ["networking", "linux", "python", "security", "ethical hacking"],
#     "Cloud Engineer": ["linux", "aws", "docker", "networking", "python"],
#     "DevOps Engineer": ["linux", "docker", "git", "kubernetes", "aws"],
#     "Business Analyst": ["excel", "sql", "statistics", "communication"]
# }
# 
# def clean(text):
#     return [x.strip().lower() for x in text.split(",") if x.strip()]
# 
# def match(skills, required):
#     return round(len(set(skills) & set(required)) / len(required) * 100, 1)
# 
# def gaps(skills, required):
#     return [x for x in required if x not in skills]
# 
# st.title("🚀 CareerPilot-X")
# st.write("AI-powered career guidance and What-If Career Lab")
# 
# st.sidebar.header("👤 Your Profile")
# 
# st.sidebar.text_input("Education", "BTech CSE-AIML")
# 
# skills_text = st.sidebar.text_input(
#     "Your Skills",
#     "python, java, pandas"
# )
# 
# skills = clean(skills_text)
# 
# # Career Match
# st.header("🎯 Career Match")
# 
# results = []
# 
# for career, required in careers.items():
#     results.append([career, match(skills, required)])
# 
# df = pd.DataFrame(results, columns=["Career", "Match %"])
# df = df.sort_values("Match %", ascending=False)
# 
# st.dataframe(df, hide_index=True, use_container_width=True)
# 
# st.success(f"⭐ Best Match: {df.iloc[0]['Career']}")
# 
# # Skill Gap
# st.header("🧠 Skill Gap Analysis")
# 
# selected = st.selectbox("Choose a career", list(careers.keys()))
# 
# required = careers[selected]
# missing = gaps(skills, required)
# 
# if missing:
#     st.warning("Skills to learn:")
#     st.write(" • ".join(missing))
# else:
#     st.success("You already have all required skills! 🎉")
# 
# # What-If Career Lab
# st.header("🔮 What-If Career Lab")
# 
# st.write("Add skills you plan to learn and see how your career match improves.")
# 
# new_skills_text = st.text_input(
#     "Skills you want to learn",
#     "machine learning, numpy, nlp"
# )
# 
# new_skills = clean(new_skills_text)
# 
# current_score = match(skills, required)
# 
# future_skills = skills + new_skills
# 
# future_score = match(future_skills, required)
# 
# col1, col2, col3 = st.columns(3)
# 
# col1.metric("Current Match", f"{current_score}%")
# col2.metric("Future Match", f"{future_score}%")
# col3.metric("Improvement", f"+{future_score-current_score:.1f}%")
# 
# st.subheader("📈 Match Improvement")
# 
# chart = pd.DataFrame({
#     "Stage": ["Current", "After Learning"],
#     "Match": [current_score, future_score]
# })
# 
# st.bar_chart(chart.set_index("Stage"))
# 
# remaining = gaps(future_skills, required)
# 
# st.subheader("🎯 Remaining Gaps")
# 
# if remaining:
#     st.write(" • ".join(remaining))
# else:
#     st.success("🎉 You have covered all required skills!")
# 
# # Roadmap
# st.header("🗺️ Learning Roadmap")
# 
# roadmap = {
#     "AI/ML Engineer": "Python → NumPy → Pandas → Machine Learning → NLP → Deep Learning",
#     "Data Scientist": "Python → Pandas → Statistics → SQL → Machine Learning",
#     "Data Analyst": "Excel → SQL → Python → Pandas → Power BI",
#     "Software Developer": "Python/Java → OOP → DSA → Git → Projects",
#     "Web Developer": "HTML → CSS → JavaScript → React → Projects",
#     "Cybersecurity Analyst": "Networking → Linux → Python → Security → Ethical Hacking",
#     "Cloud Engineer": "Linux → Networking → AWS → Docker → Projects",
#     "DevOps Engineer": "Linux → Git → Docker → Kubernetes → AWS",
#     "Business Analyst": "Excel → SQL → Statistics → Communication"
# }
# 
# st.info(roadmap[selected])
# 
# st.caption("CareerPilot-X | AI Career Guidance Assistant 🚀")

